; PlatformIO configuration for:
; Adafruit Feather ESP32-S3 No PSRAM
; ADS1015 connected over I2C / STEMMA QT

[env:adafruit_feather_esp32s3_nopsram]
platform = espressif32
board = adafruit_feather_esp32s3_nopsram
framework = arduino

; Serial Monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; External libraries
lib_deps =
    adafruit/Adafruit ADS1X15